project:
  type: website
  output-dir: docs
  render:
    - "report/05_paper.qmd"
    
format:
  html: 
    theme: 
      - cosmo
      - style.scss

website:
  favicon: figures/onsv_icon.png
  search: false
  navbar:
    background: "#fff"
    logo: figures/onsv_navbar.png
    logo-href: https://www.onsv.org.br/
    tools: 
      - icon: github
        url: https://github.com/ONSV/modelo_preditivo_onsv
      - icon: twitter
        url: https://twitter.com/_onsv
      - icon: facebook
        url: https://www.facebook.com/onsv.org.br
      - icon: instagram
        url: https://www.instagram.com/onsvoficial/
      - icon: linkedin
        url: https://www.linkedin.com/company/5010244/admin/